# Generated by Django 5.1.7 on 2025-03-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='serial_no',
            field=models.IntegerField(),
        ),
    ]
