# Generated by Django 5.1.5 on 2025-03-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_video_serial_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='desciption',
            new_name='description',
        ),
    ]
