# Generated by Django 5.1.7 on 2025-04-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_courses_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='slug',
        ),
    ]
